package Display;

import BLL.*;
import DAL.*;
import java.sql.SQLException;
import java.text.*;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author JoseOnate
 */
public class InternCarrera extends javax.swing.JInternalFrame {

    /**
     * Creates new form internCarrera
     *
     * @throws java.sql.SQLException
     */
    public InternCarrera() throws SQLException {
        initComponents();
        RadioTaxiDAL rd = new RadioTaxiDAL();
        for (String patente : rd.disponibles()) {
            this.cmbDisponibles.addItem(patente);
        }
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        Date date = new Date();
        this.txtFecha.setText(dateFormat.format(date));
        this.pnlAddCliente.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtHoraSalida = new javax.swing.JTextField();
        txtRutCliente = new javax.swing.JTextField();
        cmbDisponibles = new javax.swing.JComboBox();
        pnlAddCliente = new javax.swing.JPanel();
        txtApellido = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnIngresarCliente = new javax.swing.JButton();
        txtBusqueda = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        pnlGuardar = new javax.swing.JPanel();
        btnIngresar = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Disponibles : ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        jLabel2.setText("Fecha : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, -1, -1));

        jLabel3.setText("Hora salida : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, -1, -1));

        jLabel4.setText("Rut cliente : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        txtFecha.setEditable(false);
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 49, 87, -1));

        txtHoraSalida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtHoraSalidaFocusGained(evt);
            }
        });
        getContentPane().add(txtHoraSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 79, 87, -1));
        getContentPane().add(txtRutCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 117, 87, -1));

        getContentPane().add(cmbDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 11, 87, -1));

        pnlAddCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar Cliente"));

        jLabel5.setText("Nombre : ");

        jLabel6.setText("Apellido : ");

        btnIngresarCliente.setText("INGRESAR");
        btnIngresarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAddClienteLayout = new javax.swing.GroupLayout(pnlAddCliente);
        pnlAddCliente.setLayout(pnlAddClienteLayout);
        pnlAddClienteLayout.setHorizontalGroup(
            pnlAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddClienteLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAddClienteLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addComponent(btnIngresarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        pnlAddClienteLayout.setVerticalGroup(
            pnlAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnIngresarCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAddClienteLayout.createSequentialGroup()
                        .addGroup(pnlAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlAddCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 221, 360, -1));
        getContentPane().add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 49, 160, -1));

        jLabel7.setText("Direccion busqueda : ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 14, -1, -1));

        jLabel8.setText("Direccion destino : ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 82, -1, -1));
        getContentPane().add(txtDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 117, 160, -1));

        btnIngresar.setText("GUARDAR CARRERA");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGuardarLayout = new javax.swing.GroupLayout(pnlGuardar);
        pnlGuardar.setLayout(pnlGuardarLayout);
        pnlGuardarLayout.setHorizontalGroup(
            pnlGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGuardarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnlGuardarLayout.setVerticalGroup(
            pnlGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGuardarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 148, 360, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        RadioTaxiDAL rd = new RadioTaxiDAL();
        try {
            if (rd.existeCliente(this.txtRutCliente.getText().trim())) {
                Carrera race = new Carrera();
                race.setDire_destino(this.txtDestino.getText());
                race.setDire_inicio(this.txtBusqueda.getText());
                race.setFecha(this.txtFecha.getText());
                race.setHora_salida(this.txtHoraSalida.getText());
                race.setPatente_taxi(this.cmbDisponibles.getSelectedItem().toString());
                race.setRut_cliente(this.txtRutCliente.getText());
                if (rd.saveCarrera(race)) {
                    JOptionPane.showMessageDialog(this, "Se guardo CARRERA");
                    Taxi tx = new Taxi();
                    tx.setEstado('C');
                    tx.setPatente(this.cmbDisponibles.getSelectedItem().toString());
                    if (rd.updateTaxi(tx)) {
                        JOptionPane.showMessageDialog(this, "Se actualizo TAXI");
                        this.cmbDisponibles.removeAllItems();
                        for (String patente : rd.disponibles()) {
                            this.cmbDisponibles.addItem(patente);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "No se actualizo TAXI");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "No se guardo CARRERA");
                }
            } else {
                this.pnlGuardar.setVisible(false);
                this.pnlAddCliente.setVisible(true);
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtHoraSalidaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHoraSalidaFocusGained
        DateFormat dateFormat = new SimpleDateFormat("HH:mm");
        Date date = new Date();
        this.txtHoraSalida.setText(dateFormat.format(date));
    }//GEN-LAST:event_txtHoraSalidaFocusGained

    private void btnIngresarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarClienteActionPerformed
        RadioTaxiDAL rd = new RadioTaxiDAL();
        Cliente client = new Cliente();
        client.setNombre(this.txtNombre.getText());
        client.setApellido(this.txtApellido.getText());
        client.setRut(this.txtRutCliente.getText());
        try {
            if (rd.saveCliente(client)) {
                JOptionPane.showMessageDialog(this, "Se guardo CLIENTE");
                this.pnlAddCliente.setVisible(false);
                this.pnlGuardar.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No se guardo CLIENTE");
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnIngresarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnIngresarCliente;
    private javax.swing.JComboBox cmbDisponibles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel pnlAddCliente;
    private javax.swing.JPanel pnlGuardar;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHoraSalida;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRutCliente;
    // End of variables declaration//GEN-END:variables
}
