/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Display;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author JoseOnate
 */
public class WindowMain01 extends javax.swing.JFrame {

    /**
     * Creates new form windowMain01
     */
    public WindowMain01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpMain01 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuIngresar = new javax.swing.JMenu();
        mniCarrera = new javax.swing.JMenuItem();
        mnuVer = new javax.swing.JMenu();
        mniListado = new javax.swing.JMenuItem();
        mnuModificar = new javax.swing.JMenu();
        mniRegistrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dpMain01Layout = new javax.swing.GroupLayout(dpMain01);
        dpMain01.setLayout(dpMain01Layout);
        dpMain01Layout.setHorizontalGroup(
            dpMain01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dpMain01Layout.setVerticalGroup(
            dpMain01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        mnuIngresar.setText("Ingresar");

        mniCarrera.setText("Carrera");
        mniCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCarreraActionPerformed(evt);
            }
        });
        mnuIngresar.add(mniCarrera);

        jMenuBar1.add(mnuIngresar);

        mnuVer.setText("Ver");

        mniListado.setText("Listado cantidad carreras mensual por vehículo");
        mniListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniListadoActionPerformed(evt);
            }
        });
        mnuVer.add(mniListado);

        jMenuBar1.add(mnuVer);

        mnuModificar.setText("Modificar");

        mniRegistrar.setText("Registrar llegada vehiculo");
        mniRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniRegistrarActionPerformed(evt);
            }
        });
        mnuModificar.add(mniRegistrar);

        jMenuBar1.add(mnuModificar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpMain01)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpMain01)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCarreraActionPerformed
        InternCarrera race;
        try {
            race = new InternCarrera();
            this.dpMain01.add(race);
            race.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(WindowMain01.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_mniCarreraActionPerformed

    private void mniListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniListadoActionPerformed
        InternListado ls = new InternListado();
        this.dpMain01.add(ls);
        ls.setVisible(true);
    }//GEN-LAST:event_mniListadoActionPerformed

    private void mniRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniRegistrarActionPerformed
        InternRegistrar reg = null;
        try {
            reg = new InternRegistrar();
        } catch (SQLException ex) {
            Logger.getLogger(WindowMain01.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dpMain01.add(reg);
        reg.setVisible(true);
    }//GEN-LAST:event_mniRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowMain01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowMain01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowMain01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowMain01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new WindowMain01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpMain01;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mniCarrera;
    private javax.swing.JMenuItem mniListado;
    private javax.swing.JMenuItem mniRegistrar;
    private javax.swing.JMenu mnuIngresar;
    private javax.swing.JMenu mnuModificar;
    private javax.swing.JMenu mnuVer;
    // End of variables declaration//GEN-END:variables
}
